// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, {useLayoutEffect} from 'react';
import {View, Text, Button} from 'react-native';
import {useAuth} from '../Context/AuthContext';

const DashboardScreen = ({navigation}) => {
  const {logout} = useAuth();

  useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Button title="Logout" onPress={logout} color="#fff" />
      ),
      headerStyle: {backgroundColor: '#1976D2'},
      headerTintColor: '#fff',
      headerTitle: 'Dashboard',
    });
  }, [navigation, logout]);

  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Welcome to the Dashboard!</Text>
    </View>
  );
};

export default DashboardScreen;
