// Code Generated by Sidekick is for learning and experimentation purposes only.
/*import React from 'react';
import { createStackNavigator } from '@react-navigation/stack';
import { AuthProvider, useAuth } from '../Context/AuthContext';
import LoginScreen from '../Auth/LoginScreen';
import DashboardScreen from '../Home/DashboardScreen';
import CustomHeader from '../Components/CustomHeader';
import { TouchableOpacity, Text } from 'react-native';

const Stack = createStackNavigator();

export default function AppNavigator() {
  const { userToken, logout, loading } = useAuth();

  if (loading) return null; // Or a splash screen

  return (
    <Stack.Navigator
      screenOptions={({ navigation, route }) => ({
        header: (props) => {
          let title = props.options.title || props.route.name;
          let rightComponent = null;
          let onBack = navigation.canGoBack() ? navigation.goBack : null;

          if (route.name === 'Dashboard') {
            rightComponent = (
              <TouchableOpacity onPress={logout}>
                <Text style={{ color: '#fff', fontWeight: 'bold' }}>Logout</Text>
              </TouchableOpacity>
            );
            onBack = null;
          }

          return (
            <CustomHeader
              title={title}
              onBack={onBack}
              rightComponent={rightComponent}
            />
          );
        },
      })}
    >
      {userToken ? (
        <Stack.Screen name="Dashboard" component={DashboardScreen} options={{ title: 'Dashboard' }} />
      ) : (
        <Stack.Screen name="Login" component={LoginScreen} options={{ title: 'Login' }} />
      )}
    </Stack.Navigator>
  );
}*/

import AuthNavigator from "./AuthNavigatior";
import DashboardNavigator from "./DashboardNavigator";
import { useAuth } from '../Context/AuthContext';

export default function AppNavigator() {
  const { userToken, logout, loading } = useAuth();

  if (loading) return null; // Or a splash screen

  return userToken ? <DashboardNavigator logout={logout} /> : <AuthNavigator />;
}

// export default function App() {
//   return (
//     <AuthProvider>
//       <NavigationContainer>
//         <AppStack />
//       </NavigationContainer>
//     </AuthProvider>
//   );
// }
