// Code Generated by Sidekick is for learning and experimentation purposes only.
/*import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';

const CustomHeader = ({ title, onBack, rightComponent }) => (
  <View style={styles.container}>
    {onBack ? (
      <TouchableOpacity onPress={onBack} style={styles.backButton}>
        <Text style={styles.backText}>{"<"}</Text>
      </TouchableOpacity>
    ) : (
      <View style={styles.backButton} />
    )}
    <Text style={styles.title}>{title}</Text>
    <View style={styles.right}>{rightComponent}</View>
  </View>
);

const styles = StyleSheet.create({
  container: {
    height: 80,
    backgroundColor: '#1976D2', // Theme color
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    alignItems: 'flex-start',
    backgroundColor:'red'
  },
  backText: {
    color: '#fff',
    fontSize: 24,
  },
  title: {
    flex: 1,
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
    backgroundColor: 'red',
    marginBottom:-40
    // marginBottom: -20,
    // margin:20
  },
  right: {
    width: 40,
    alignItems: 'flex-end',
    backgroundColor:'red'
  },
});

export default CustomHeader;*/

// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import colors from '../Constants/Constants';

const CustomHeader = ({ title, onBack, rightComponent }) => (
  <SafeAreaView edges={['top']} style={styles.safeArea}>
    <View style={styles.container}>
      {onBack ? (
        <TouchableOpacity onPress={onBack} style={styles.backButton}>
          <Text style={styles.backText}>{"<"}</Text>
        </TouchableOpacity>
      ) : (
        <View style={styles.backButton} />
      )}
      <Text style={styles.title} numberOfLines={1} ellipsizeMode="tail">
        {title}
      </Text>
      <View style={styles.right}>{rightComponent}</View>
    </View>
  </SafeAreaView>
);

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.primary,
  },
  container: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    backgroundColor: colors.primary,
  },
  backButton: {
    width: 40,
    alignItems: 'flex-start',
    //  backgroundColor:'red'
  },
  backText: {
    color: '#fff',
    fontSize: 24,
  },
  title: {
    flex: 1,
    color: colors.whileColor,
    fontSize: 20,
    textAlign: 'center',
    marginHorizontal: 8,
    fontWeight:'600'
    //  backgroundColor:'red'
  },
  right: {
    width: 40,
    alignItems: 'flex-end',
  },
});

export default CustomHeader;

/*
// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const CustomHeader = ({ title, onBack, rightComponent }) => (
  <SafeAreaView edges={['top']} style={styles.safeArea}>
    <View style={styles.container}>
      {onBack ? (
        <TouchableOpacity onPress={onBack} style={styles.sideButton}>
          <Text style={styles.sideText}>{"<"}</Text>
        </TouchableOpacity>
      ) : (
        <View style={styles.sideButton} />
      )}
      <Text style={styles.title} numberOfLines={1} ellipsizeMode="tail">
        {title}
      </Text>
      <View style={styles.sideButton}>{rightComponent}</View>
    </View>
  </SafeAreaView>
);

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#1976D2',
  },
  container: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    backgroundColor: '#1976D2',
  },
  sideButton: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideText: {
    color: '#fff',
    fontSize: 24,
  },
  title: {
    flex: 1,
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
    marginHorizontal: 8,
  },
});

export default CustomHeader;

 */