// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import AppTextField from '../Components/AppTextField';
import AppButton from '../Components/AppButton';
// import ForgotPasswordScreen from './ForgotPassword';
import { useAuth } from '../Context/AuthContext';

const LoginScreen = ({ navigation }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [errors, setErrors] = useState({});

  const { login } = useAuth();

  // const handleLogin = () => {
  //   // Replace with real authentication logic
    
  // };

  const handleLogin = () => {
    console.log("handleLogin LoginScreen");
    console.warn("warn handleLogin LoginScreen");
    const validationErrors = validateFields(email, password);
    setErrors(validationErrors);
    if (Object.keys(validationErrors).length === 0) {
      // Proceed with login
      login('dummy-token');
      // navigation.replace('Dashboard');
    }
  };

const validateFields = (email, password) => {
  const errors = {};

  // Simple email regex for demonstration
  const emailRegex = /\S+@\S+\.\S+/;
  if (!email || !emailRegex.test(email)) {
    errors.email = 'Please enter a valid email address.';
  }

  if (!password) {
    errors.password = 'Password is required.';
  }

  return errors;
};

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Personal Finance Tracker</Text>
      <AppTextField
        placeholder="Email"
        value={email}
        onChangeText={setEmail}
        keyboardType="email-address"
        autoCapitalize="none"
      />
      {errors.email ? <Text style={styles.errorText}>{errors.email}</Text> : null}
      <AppTextField
        placeholder="Password"
        value={password}
        onChangeText={setPassword}
        secureTextEntry
      />
      {errors.password ? <Text style={styles.errorText}>{errors.password}</Text> : null}
      <TouchableOpacity style={{alignSelf: 'flex-end', marginBottom: 10}} onPress={() => navigation.navigate('ForgotPassword')}>
        <Text style={styles.forgotButtonText}>Forgot Password?</Text>
      </TouchableOpacity>
      <AppButton title="Login" onPress={handleLogin} />
      <TouchableOpacity onPress={() => navigation.navigate('Register')}>
        <Text style={styles.signupButtonText}>Don't have an account? Signup</Text>
      </TouchableOpacity>
      <TouchableOpacity
        onPress={() => navigation.navigate('Login')}
        style={{ alignSelf: 'flex-end', marginTop: 16, backgroundColor:'red' }}
      >
        <Text style={{ color: '#487eb0', fontSize: 15 }}>
          Already have an account? <Text style={{ fontWeight: 'bold' }}>Sign in</Text>
        </Text>
    </TouchableOpacity>

      {/* <TouchableOpacity onPress={() => navigation.navigate('ForgotPassword')}>
        <Text style={styles.forgotText}>Forgot Password?</Text>
      </TouchableOpacity> */}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#f5f6fa',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#273c75',
    marginBottom: 32,
    alignSelf: 'center',
  },
  signupButtonText: {
    color: '#487eb0',
    fontSize: 15,
    textAlign: 'center',
    marginTop: 8,
    // backgroundColor:'red'
  },
  forgotButtonText: {
    color: '#487eb0',
    fontSize: 15,
    paddingHorizontal: 10,
    textAlign: 'right',
    // marginTop: 8,
    // marginRight: 10,
    // backgroundColor:'red',
    // marginBottom: 8,
  },
  errorText: {
    color: '#e84118',
    fontSize: 12,
    marginBottom: 10,
    marginLeft: 4,
  },
});

export default LoginScreen;
