// Code Generated by Sidekick is for learning and experimentation purposes only.
export const validateRegisterFields = ({ firstName, lastName, email, mobile, password }) => {
  const errors = {};
  if (!firstName) errors.firstName = 'First name is required.';
  if (!lastName) errors.lastName = 'Last name is required.';

  const emailRegex = /\S+@\S+\.\S+/;
  if (!email || !emailRegex.test(email)) errors.email = 'Enter a valid email address.';

  const mobileRegex = /^[0-9]{10}$/;
  if (!mobile || !mobileRegex.test(mobile)) errors.mobile = 'Enter a valid 10-digit mobile number.';

  if (!password || password.length < 6) errors.password = 'Password must be at least 6 characters.';

  return errors;
};

export const validateEmailField = (email) => {
  const errors = {};
  const emailRegex = /\S+@\S+\.\S+/;
  if (!email || !emailRegex.test(email)) errors.email = 'Enter a valid email address.';
  console.log("errors", errors);
  return errors;
};
